language: node_js

node_js:
  - "10"
install:
  - npm install

script:
    - npm run build

deploy:
  stage: deploy
  provider: pages
  skip_cleanup: true
  github_token: $GIT_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master